wordpress:
  build: wordpress/.
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80
  volumes:
    - /var/www/html:/var/www/html

wordpress_db:
  image: mysql
  environment:
    MYSQL_DATABASE: wordpress

nginx:
  build: nginx/.
  ports:
    - 80:80
  links:
    - wordpress