FROM php:5.6-fpm

# install the PHP extensions we need
RUN apt-get update && apt-get install -y libpng12-dev libjpeg-dev && rm -rf /var/lib/apt/lists/* \
	&& docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
	&& docker-php-ext-install gd
RUN docker-php-ext-install mysqli
 
ADD wordpress /var/www/html
COPY wp-config.php /var/www/html/wordpress/

RUN chown -R www-data:www-data /var/www/html/wordpress

COPY docker-entrypoint.sh /entrypoint.sh

# grr, ENTRYPOINT resets CMD now

ENTRYPOINT ["/entrypoint.sh"]
VOLUME ["/var/www/html"]
CMD ["php-fpm"]